site:
  name: example

global:
  pattern: multicluster-devsecops
  repoURL: "https://github.com/pattern-clone/multicluster-devsecops"
  targetRevision: main

  git:
    hostname: github.com
    account: PLAINTEXT
    username: PLAINTEXT
    email: SOMEWHERE@EXAMPLE.COM
    dev_revision: main

  imageregistry:
    account: PLAINTEXT
    hostname: quay.io
    type: quay

devel:
  appURL: AUTOMATED
  image: quay.io/smileyfritz/chat-client:latest
clusterGroup:
  name: testgroup
