apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-cluster-init
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-cluster-init
subjects:
  - kind: ServiceAccount
    name: create-cluster-init
    namespace: stackrox

