global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

clusterGroup:
  name: development
  isHubCluster: false
  clusterName: wh-dev

  namespaces:
    - stackrox
    - policies
    - openshift-pipelines
    - devsecops-ci
    - config-demo
  
  subscriptions:
  - name: rhacs-operator  #packageName
    namespace: openshift-operators # operator namespace
    channel: rhacs-3.68
    csv: rhacs-operator.v3.68.1

  - name: openshift-pipelines-operator-rh
    namespace: openshift-operators
    channel: pipelines-1.7
    csv: openshift-pipelines-operator.v1.7.1

  - name: quay-bridge-operator
    namespace: openshift-operators
    channel: stable-3.7
    csv: quay-bridge-operator.v3.7

  projects:
    - secured
    - ci
    - test-app

  applications:
  - name: acs-secured
    namespace: stackrox
    project: secured
    path: common/acs/secured

  - name: pipelines
    namespace: devsecops-ci
    project: ci
    path: charts/region/pipelines

  - name: quay-integration
    namespace: openshift-operators
    project: secured
    path: charts/region/quay

  - name: acs-integration
    namespace: stackrox
    project: ci
    path: charts/region/acs

  - name: config-demo-test
    namespace: config-demo
    project: test-app
    path: charts/all/config-demo

#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#  - name: pipelines
#    namespace: production
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: stable
#    overrides:
#    - name: myparam
#      value: myparam
#
#  - name: pipelines
#    namespace: staging
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: main