# Possibly still not the right home...
devel: 
  image: chat-client:latest
  npmbase: quay.io/hybridcloudpatterns/ubi-npm
  namespace: devsecops-ci
  roxCTLImage: registry.access.redhat.com/advanced-cluster-security/rhacs-roxctl-rhel8:3.71.0-5

global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic
  
  cicd:
    namespace: devsecops-ci

  app:
    gatling:
      image: quay.io/hybridcloudpatterns/gatling:latest
      repo: https://github.com/hybrid-cloud-demos/spring-petclinic-gatling
    zapImage: quay.io/hybridcloudpatterns/zap2docker-stable
    crdaImage: quay.io/hybridcloudpatterns/crda-image:0.1
    petclinic:
      repo: https://github.com/hybrid-cloud-demos/spring-petclinic
      configRepo: https://github.com/hybrid-cloud-demos/spring-petclinic-config
      image: quay.io/hybridcloudpatterns/spring-petclinic:latest

  git:
    taskImage: image-registry.openshift-image-registry.svc:5000/openshift/tools

clusterGroup:
  name: devel
  isHubCluster: false

  namespaces:
    - argo-rollouts
    - stackrox
    - policies
    - openshift-pipelines
    - devsecops-ci
    - devsecops-dev
    - devsecops-qa

  subscriptions:
    rhacs-operator:
      name: rhacs-operator  #packageName
      namespace: openshift-operators # operator namespace

    openshift-pipelines:
      name: openshift-pipelines-operator-rh
      namespace: openshift-operators

    quay-bridge-operator:
      name: quay-bridge-operator
      namespace: openshift-operators

  projects:
    - secured
    - ci
    - test-app
#Adding jchraibi #advanced-devsecops to pattern framework
    - spring-petclinic
    - rollouts

  applications:
    acs-secured:
      name: acs-secured
      namespace: stackrox
      project: secured
      path: charts/hub/acs/secured

    argo-rollouts:
      name: argo-rollouts
      namespace: argo-rollouts
      project: rollouts
      path: charts/region/rollouts

    pipelines:
      name: pipelines
      namespace: devsecops-ci
      project: ci
      path: charts/region/pipelines
      ignoreDifferences:
      - kind: ServiceAccount
        jsonPointers:
        - /imagePullSecrets
        - /secrets

    quay-integration:
      name: quay-integration
      namespace: openshift-operators
      project: secured
      path: charts/region/quay

    acs-integration:
      name: acs-integration
      namespace: stackrox
      project: ci
      path: charts/region/acs

    nexus:
      name: nexus
      namespace: devsecops-ci
      project: ci
      path: charts/region/nexus

    reports-repo:
      name: reports-repo
      namespace: devsecops-ci
      project: ci
      path: charts/region/reports

    sonarqube:
      name: sonarqube
      namespace: devsecops-ci
      project: ci
      path: charts/region/sonarqube

    cosign:
      name: cosign
      namespace: devsecops-ci
      project: ci
      path: charts/region/cosign

    rekor:
      name: rekor
      namespace: devsecops-ci
      project: ci
      path: charts/region/rekor

    roxctl:
      name: roxctl
      namespace: devsecops-ci
      project: ci
      path: charts/region/roxctl

#Adding jchraibi #advanced-devsecops to pattern framework
    staging-spring-petclinic:
      name: staging-spring-petclinic
      namespace: devsecops-qa
      project: spring-petclinic
      path: charts/region/stage/spring-petclinic-config

    
    dev-spring-petclinic:
      name: dev-spring-petclinic
      namespace: devsecops-dev
      project: spring-petclinic
      path: charts/region/spring-petclinic-config

#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#  - name: pipelines
#    namespace: production
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: stable
#    overrides:
#    - name: myparam
#      value: myparam
#
#  - name: pipelines
#    namespace: staging
#
#   project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: main
