apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: containers-pvc
  namespace: devsecops-ci
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
  volumeMode: Filesystem
  volumeBindingMode: Immediate
  accessModes:
    - ReadWriteOnce
