apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "6"
  name: wait-for-quay-app-deploy
  namespace: {{ .Values.quay.namespace }}
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          # wait for the operator QuayRegistry CR to be available
          oc wait QuayRegistry quay-registry --for=condition=Available=true
        name: wait-for-quay-app
      dnsPolicy: ClusterFirst
      activeDeadlineSeconds: 900
      restartPolicy: Never
      serviceAccountName: quay-admin-sa
      terminationGracePeriodSeconds: 60
