apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: local-registry
  namespace: quay-enterprise
spec:
  components:
{{- range .Values.quay.component }}
    - kind: {{ .name }}
      managed: {{ .managed | default "false" }}
{{- end }}
{{- if .Values.quay.configBundleSecret.deploy }}
  configBundleSecret: {{ .Values.quay.configBundleSecret.name }}
{{- end }}
