apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: quay-admin-binding
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: quay-admin-role
subjects:
  - kind: ServiceAccount
    name: quay-admin-sa
    namespace: {{ .Values.quay.namespace }}

