apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: react-pipelinerun
spec:
  params: 
    - name: "github-repo-revision"
      value: "main"
    - name: "github-repo-url"
      value: {{ .Values.devel.appURL }}
    - name: "context-dir"
      value: "/"
    - name: "image-name" 
      value: {{ .Values.devel.image }}
    - name: "is-name"
      value: "chat-client"
  pipelineRef:
    name: build-and-deploy
  podTemplate:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      volumes:
        - name: varlibcontainers
          persistentVolumeClaim:
            claimName: containers-pvc2
  serviceAccountName: pipeline-svc
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: pipeline-pvc1