---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reports-repo
    app.kubernetes.io/instance: reports-repo
    app.kubernetes.io/name: reports-repo
    app.kubernetes.io/part-of: reports-repo
  name: reports-repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reports-repo
      deployment: reports-repo
  template:
    metadata:
      labels:
        app: reports-repo
        deployment: reports-repo
    spec:
      containers:
      - name: uploader
        image: quay.io/chmouel/go-simple-uploader:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: UPLOADER_PORT
            value: "9000"
          - name: UPLOADER_DIRECTORY
            value: "/fileuploads"
        volumeMounts:
        - mountPath: /fileuploads
          name: staticfiles
      - image: quay.io/siamaksade/nginx:latest
        name: nginx
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: nginx-conf
        - mountPath: /fileuploads
          name: staticfiles
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-pv
      volumes:
      - configMap:
          defaultMode: 420
          name: reports-repo-nginx-conf
        name: nginx-conf
      - name: staticfiles
        persistentVolumeClaim:
          claimName: reports-repo-pv
